### ISSUE TITLE
Keras modlel load error when launching vision.launch

### ISSUE THREAD

**Issue by RaduCorcodel** [pablomalvido/vision_pkg_full_demo#1]
Hi,

I'm trying to launch ```roslaunch vision_pkg_full_demo vision.launch``` and I'm met with the following error:
```
Traceback (most recent call last):
  File "/homes/corcodel/ws_cable_detection/src/vision_pkg_full_demo/src/TAU_supervisor.py", line 314, in <module>
    DLO_model = tf.keras.models.load_model(path_model, compile=False)
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/site-packages/keras/src/saving/saving_api.py", line 206, in load_model
    raise ValueError(
ValueError: File format not supported: filepath=/homes/corcodel/ws_cable_detection/src/vision_pkg_full_demo/src/../models/my_model_v1. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(/homes/corcodel/ws_cable_detection/src/vision_pkg_full_demo/src/../models/my_model_v1, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).
```

My system is Ubuntu 20.04, ROS Noetic, Python 3.9, Tensoflow 2.18.0, Keras 3.6.0

Any ideas what might be the problem? I did noticed there's no *.h5 or *.hdf5 file in my_model_v1 in the repo

Thank you.

Best,
Radu

**Comment by RaduCorcodel** [comment]
OK, I think I'm inching to the solution. It's a compatibility error. I installed Keras 2.15 and Tensorflow 1.4. Different error now but at least it reads the model... sort of...
```
Traceback (most recent call last):
  File "/homes/corcodel/ws_cable_detection/src/vision_pkg_full_demo/src/TAU_supervisor.py", line 314, in <module>
    DLO_model = tf.keras.models.load_model(path_model, compile=False)
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 146, in load
    keras_loader.load_layers(compile=compile)
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 378, in load_layers
    self.loaded_nodes[node_metadata.node_id] = self._load_layer(
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 420, in _load_layer
    obj, setter = self._revive_from_config(identifier, metadata, node_id)
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 444, in _revive_from_config
    self._add_children_recreated_from_config(
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 305, in _add_children_recreated_from_config
    metadata = json_utils.decode(proto.user_object.metadata)
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 62, in decode
    return json.loads(json_string, object_hook=_decode_helper)
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/homes/corcodel/anaconda3/envs/cable_detection/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Can you please do a conda list of your working version and attach it to this thread? Looks like I need to match the exact versions of different libraries.

Thank you.

Radu,

**Comment by pablomalvido** [comment]
Hi Radu,

Thanks for your interest. I will come back to you and update the information in the README file before the end of the week.

Best regards,
Pablo

**Comment by RaduCorcodel** [comment]
Hi Pablo,

I had some time to poke around a bit more and I can run it now with Tensorflow 2.12. It would still be useful to have a requirements.txt file in the repo to install everything in one go. But I think we can close the thread now.
Thank you for getting back to me.

Best regards,
Radu

**Comment by pablomalvido** [comment]
Hi Radu @RaduCorcodel,

I have just updated the repository including a detailed description of the main dependencies. I also corrected some minor bugs and encapsulated the main functionalities of the algorithm as ROS Services. You can find a detailed description of how to use them in the updated README file. Additionally, you can find some examples of the system performance in the plots/ and imgs/ folders, which are the result of applying these services to the images in the test_images/ directory. Finally, I have also provided some example service calls (calls.txt) you can use to test the ROS services and the system functionalities for the images in the test_images/ directory. You can play with the parameters of the services (forward, iteration, segm_opt, pixel_D) to optimize your results.

If you have any other question or you need support, don't hesitate to get in touch with me.

Best regards,
Pablo
